root@127.0.0.1:10022: 
    roles: [centos]
    context: 
        accounts: [root, jjm]
        hostname: centos-vbox
root@127.0.0.1:20022: 
    roles: [debian, debian-testing, debian-systemd, debian-nginx]
    context: 
        accounts: [root, jjm]
        hostname: debian-vbox
        nginx:
            test-site: |
                server {
                    listen      80;
                    server_name test;
                    location /hello {
                        uwsgi_pass  unix:/run/uwsgi/hello.sock;
                        include     /etc/nginx/uwsgi_params;
                    }
                }
